# Generated by Django 4.0.4 on 2022-04-30 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻名称')),
                ('newsType', models.CharField(choices=[('学校新闻', '学校新闻'), ('通知公告', '通知公告'), ('院部动态', '院部动态')], max_length=50, verbose_name='新闻类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '学校新闻',
                'verbose_name_plural': '学校新闻',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='newsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='news/', verbose_name='新闻图片')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsImgs', to='news.news', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '新闻图片',
                'verbose_name_plural': '新闻图片',
            },
        ),
    ]
