# Generated by Django 4.0.4 on 2022-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimg',
            name='photo_title',
            field=models.CharField(default=1, max_length=10, verbose_name='图片描述'),
            preserve_default=False,
        ),
    ]
