# Generated by Django 4.0.4 on 2022-04-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimg_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimg',
            name='photo_title',
            field=models.CharField(blank=True, max_length=10, verbose_name='图片描述'),
        ),
    ]
