# Generated by Django 2.2.4 on 2022-04-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220501_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='新闻描述'),
        ),
        migrations.CreateModel(
            name='newsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=10, verbose_name='图片描述')),
                ('photo', models.ImageField(blank=True, upload_to='news/', verbose_name='新闻图片')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsImgs', to='news.News', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '新闻图片',
                'verbose_name_plural': '新闻图片',
            },
        ),
    ]
