# Generated by Django 3.2.3 on 2023-04-27 04:38

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20230427_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='新闻描述'),
        ),
    ]
