# Generated by Django 3.2.3 on 2023-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0002_mynew_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
