# Generated by Django 2.2.4 on 2022-04-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_alter_lunbo_main_options_alter_lunbo_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo_main',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lunbo_video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
