# Generated by Django 2.2.4 on 2022-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
