# Generated by Django 2.2.4 on 2022-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieApp', '0002_delete_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='School_Photo/')),
            ],
        ),
    ]
