# Generated by Django 2.2.4 on 2022-05-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_auto_20220523_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_photo',
            options={'ordering': ['-publishDate'], 'verbose_name': '学校风光', 'verbose_name_plural': '学校风光'},
        ),
    ]
